[test]
root = "src"
smol = false

# Exclude files from code coverage reports
coveragePathIgnorePatterns = [
  "lib/**",
  "src/__tests__/helpers/**",
  "src/__tests__/fixtures/**",
  "src/mock/**",
]
